# Site settings
title: Damien Cornu
email: dcornu@iciq.es
description: > # this means to ignore newlines until "baseurl:"
  Lecturer in heterogeneous catalysis, specialized in spectroscopy and in DFT calculations <br />
twitter_username: damienaberlin
github_username:  dacornu
researchgate_username: cornu

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Post-doc"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
